// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8IIustKoFUFh4WlTYC0sqA03TrhiL2nw',
    appId: '1:632597314673:web:0d7150060e2da1f75bafd0',
    messagingSenderId: '632597314673',
    projectId: 'matermich-7828c',
    authDomain: 'matermich-7828c.firebaseapp.com',
    storageBucket: 'matermich-7828c.appspot.com',
    measurementId: 'G-1XJDRZTFFT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCfPSoZoPzO2btebU5stDzI--Ew7AhTeE',
    appId: '1:632597314673:android:d589a7d6602b6f3f5bafd0',
    messagingSenderId: '632597314673',
    projectId: 'matermich-7828c',
    storageBucket: 'matermich-7828c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZf3MakyeXFfYQZYoWwtiVdlqqOhSU2oo',
    appId: '1:632597314673:ios:e9dc87f982e6aa5e5bafd0',
    messagingSenderId: '632597314673',
    projectId: 'matermich-7828c',
    storageBucket: 'matermich-7828c.appspot.com',
    iosBundleId: 'com.example.matermich',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZf3MakyeXFfYQZYoWwtiVdlqqOhSU2oo',
    appId: '1:632597314673:ios:e9dc87f982e6aa5e5bafd0',
    messagingSenderId: '632597314673',
    projectId: 'matermich-7828c',
    storageBucket: 'matermich-7828c.appspot.com',
    iosBundleId: 'com.example.matermich',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8IIustKoFUFh4WlTYC0sqA03TrhiL2nw',
    appId: '1:632597314673:web:4d081066e9ce87f85bafd0',
    messagingSenderId: '632597314673',
    projectId: 'matermich-7828c',
    authDomain: 'matermich-7828c.firebaseapp.com',
    storageBucket: 'matermich-7828c.appspot.com',
    measurementId: 'G-ZS94WEQL2S',
  );
}
